local set = vim.keymap.set

-- Plugin: nvim-dap
set("n", "<F6>", function()
	require("dap").continue()
end, { silent = true, desc = "debug: Run/Continue" })
set("n", "<F7>", function()
	require("dap").terminate()
end, { silent = true, desc = "debug: Stop" })
set("n", "<F8>", function()
	require("dap").toggle_breakpoint()
end, { silent = true, desc = "debug: Toggle breakpoint" })
set("n", "<F9>", function()
	require("dap").step_into()
end, { silent = true, desc = "debug: Step into" })
set("n", "<F10>", function()
	require("dap").step_out()
end, { silent = true, desc = "debug: Step out" })
set("n", "<F11>", function()
	require("dap").step_over()
end, { silent = true, desc = "debug: Step over" })
set("n", "<leader>db", function()
	require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { silent = true, desc = "debug: Set conditional breakpoint" })
set("n", "<leader>dc", function()
	require("dap").run_to_cursor()
end, { silent = true, desc = "debug: Run to cursor" })
set("n", "<leader>dl", function()
	require("dap").run_last()
end, { silent = true, desc = "debug: Run last" })
set("n", "<leader>do", function()
	require("dap").repl.open()
end, { silent = true, desc = "debug: Open REPL" })
