local set = vim.keymap.set

set("n", "<leader>ff", function()
	require("snacks").picker.smart()
end, { silent = true, desc = "find: Files" })
set("n", "<leader>fb", function()
	require("snacks").picker.buffers()
end, { silent = true, desc = "find: Buffers" })
set("n", "<leader>fp", function()
	require("snacks").picker.grep()
end, { silent = true, desc = "find: Live grep" })
set("v", "<leader>fs", function()
	require("snacks").picker.grep_word()
end, { silent = true, desc = "find: Grep selection" })
set("n", "<leader>fu", function()
	require("snacks").picker.undo()
end, { silent = true, desc = "find: Undo history" })
set("n", "<leader>fr", function()
	require("snacks").picker.resume()
end, { silent = true, desc = "find: Resume last" })
